const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const steps=[['Check-in','Der Einstieg ins Wallet','Am Mobile-Wallet-Kiosk scannt der Gast einen QR-Code. Registrierte Spieler werden eingecheckt.','Mobile Wallet Kiosk','↗','Willkommen','QR am Kiosk scannen','Check-in'],['Registrierung','Ein Link zum persönlichen Zugang','Neue Spieler senden eine leere SMS und erhalten den Link zur Registrierungswebsite. Dort wird das Wallet sichtbar.','SMS & Website','✉','Registrierung','SMS → Link → Website','Wallet öffnen'],['Einzahlung','Guthaben am POS aufladen','Laut Folder erfolgt die Einzahlung ausschließlich direkt beim Mitarbeiter am POS. Das Wallet zeigt das bereitgestellte Guthaben.','Betreuter POS','＋','Wallet bereit','Einzahlung beim POS-Mitarbeiter','Guthaben bereit'],['Verbindung','Vom Wallet zum Terminal','Über die Website scannt der Gast den Terminal-QR. Guthaben wird vom Wallet auf das Terminal übertragen.','Website & Terminal','⇄','Terminal verbinden','QR scannen · Guthaben übertragen','Verbindung hergestellt'],['Spielen','Am Terminal spielen','Die Spielsession läuft am Terminal bis zum Cashout. Das Wallet verbindet den Zugang mit dem Guthabenprozess.','Gaming-Terminal','▥','Spielsession','Wallet → Terminal','Session aktiv'],['Auszahlung','Zurück zum betreuten POS','Cashout beendet die Terminalnutzung. Die Auszahlung erfolgt beim POS-Mitarbeiter mit Bestätigung über eine Withdrawal-PIN.','POS & Withdrawal-PIN','✓','Auszahlung','Bestätigung beim POS per PIN','Vorgang bestätigt']];
let currentStep=0;$('#steps').innerHTML=steps.map((x,i)=>`<button class="step" role="tab" id="step-${i}" aria-controls="step-panel" data-step="${i}"><span>0${i+1}</span><strong>${x[0]}</strong></button>`).join('');
function selectStep(i){currentStep=(i+steps.length)%steps.length;let s=steps[currentStep];$$('[data-step]').forEach((b,n)=>{b.classList.toggle('active',n===currentStep);b.setAttribute('aria-selected',n===currentStep);b.tabIndex=n===currentStep?0:-1});$('#step-panel').setAttribute('aria-labelledby',`step-${currentStep}`);$('#step-title').textContent=s[1];$('#step-text').textContent=s[2];$('#step-location').textContent=s[3];$('#step-count').textContent=`0${currentStep+1} / 06`;$('#phone-ui').innerHTML=`<div class="ui-icon">${s[4]}</div><div class="ui-title">${s[5]}</div><div class="ui-card">${s[6]}</div><div class="ui-bar">${s[7]}</div>`}
$$('[data-step]').forEach(b=>b.onclick=()=>selectStep(+b.dataset.step));$('#prev').onclick=()=>selectStep(currentStep-1);$('#next').onclick=()=>selectStep(currentStep+1);selectStep(0);
const nodes={cloud:['Zentrale Dienste','Country Server','Der Folder beschreibt einen zentralen, von Vnet betriebenen und gewarteten Cloud-Country-Server.',['Datenbank und Data Service','Ticket Validation und RNG-Dienste','Web Reporting & Management']],wallet:['Cashless Zugang','Mobile Wallet','Wallet-basierter Zugang ist über Smartphone, Check-in-Kiosk oder Smartcard vorgesehen.',['RFID/NFC, Magnetstreifen oder Kontaktchip','Anonyme oder registrierte Spielerprofile','KYC als Grundlage für Player Management']],pos:['Lokaler Betrieb','POS & Outlet','Die lokale Standortebene verbindet Betreuung, Zahlungen und Terminalübersicht.',['POS-Terminal mit Outlet-Komponenten','Ein- und Auszahlung beim Mitarbeiter','Router, Scanner und Drucker je Ausstattung']],terminal:['Gaming-Endpunkt','EGM & VLT','Die Terminalebene ist in Guthabenprozesse, Steuerung und Berichte eingebunden.',['Terminal Control und Spielinformationen','Ereignisse und Statusmeldungen','Jackpot-Display und Controller im Standortaufbau']],report:['Betriebsübersicht','Reporting & Management','Das Web Reporting and Management Interface bündelt Informationen für unterschiedliche Rollen.',['Reports nach Spiel, Terminal, Outlet oder Land','Nutzer und Berechtigungen verwalten','Jackpots, Cashback und Bonusing konfigurieren']]};
$$('[data-node]').forEach(b=>b.onclick=()=>{let d=nodes[b.dataset.node];$$('[data-node]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',n===b)});$('#node-detail').innerHTML=`<span class="tag">${d[0]}</span><h3>${d[1]}</h3><p>${d[2]}</p><ul>${d[3].map(x=>`<li>${x}</li>`).join('')}</ul>`});$('[data-node="cloud"]').click();
const reports=[['Game Breakdown','Das Spiel im Detail.','Spielbezogene Statistiken machen Runden, Einsätze, Gewinne und weitere Kennzahlen eines gewählten Zeitraums sichtbar.',['Spielrunden und Freispiele','Bets, Wins und Auszahlungsquote','Auswertung je Spiel oder Theme'],['12.480','Runden / Beispiel','6','Themes / Beispiel'],[35,52,46,65,61,90,78]],['Accounting','Den Geldfluss überblicken.','Finanzielle Daten nach Standort, Geschäftstag und bei Bedarf Terminal zusammenführen.',['Bets, Wins und Hold','Standort- und Terminalebene','Periodische Betriebsberichte'],['$24.960','Bets / Beispiel','$21.216','Wins / Beispiel'],[47,39,63,76,55,84,70]],['Active Terminals','Verfügbarkeit im Blick.','Aktive Terminaltage mit Online-Tagen vergleichen, als Übersicht oder im Detail.',['Lieferant, Outlet oder Unternehmen','Aktive Terminaltage','Vergleich mit Online-Tagen'],['48','Terminals / Beispiel','336','Online-Tage / Beispiel'],[80,84,82,90,87,92,86]],['Events','Ereignisse nachvollziehen.','Ereignisse ausgewählter Geräte nach Geschäftstag und Standort untersuchen.',['Gerätebezogene Ereignisse','Fehlerbeschreibungen im Alarms Screen','Farbige Warnanzeigen im POS'],['18','Ereignisse / Beispiel','3','Hinweise / Beispiel'],[32,20,58,38,80,27,42]]];
$('#report-tabs').innerHTML=reports.map((r,i)=>`<button role="tab" id="report-${i}" aria-controls="report-panel" data-report="${i}">${r[0]}</button>`).join('');
$$('[data-report]').forEach(b=>b.onclick=()=>{let r=reports[+b.dataset.report];$$('[data-report]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-selected',n===b);n.tabIndex=n===b?0:-1});$('#report-panel').setAttribute('aria-labelledby',b.id);$('#report-title').textContent=r[1];$('#report-desc').textContent=r[2];$('#report-bullets').innerHTML=r[3].map(x=>`<li>${x}</li>`).join('');$('#metrics').innerHTML=`<div><b>${r[4][0]}</b><small>${r[4][1]}</small></div><div><b>${r[4][2]}</b><small>${r[4][3]}</small></div>`;$('#chart').innerHTML=r[5].map((x,i)=>`<div class="bar" style="height:${x}%" role="img" aria-label="${['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][i]}: illustrativer Index ${x}"></div>`).join('')});$('[data-report]').click();
const markets=[['2010','Österreich'],['2011','Slowakei'],['2013','Rumänien'],['2017','Sambia'],['2018','Moldau'],['2019','Nigeria · Uganda'],['2022','Tansania · Karibik'],['2024','Eswatini · Brasilien']];$('#years').innerHTML=markets.map((x,i)=>`<button role="tab" data-year="${i}" aria-controls="market-title">${x[0]}</button>`).join('');$$('[data-year]').forEach(b=>b.onclick=()=>{$$('[data-year]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-selected',n===b);n.tabIndex=n===b?0:-1});let m=markets[+b.dataset.year];$('#market-year').textContent=m[0];$('#market-title').textContent=m[1];$('#market-title').parentElement.querySelector('p').textContent=m[0]==='2022'?'Karibik laut Folder: Antigua und Barbuda, Barbados, Saint Lucia, St. Kitts and Nevis, Sint Maarten, Guyana und Puerto Rico.':'Im Folder genannte Referenzmärkte.'});$('[data-year="7"]').click();
// Keyboard-complete tabs, usable without mouse or animation.
$$('[role="tablist"]').forEach(list=>list.addEventListener('keydown',e=>{let tabs=[...list.querySelectorAll('[role="tab"]')],idx=tabs.indexOf(document.activeElement);if(idx<0)return;let target=e.key==='ArrowRight'?(idx+1)%tabs.length:e.key==='ArrowLeft'?(idx-1+tabs.length)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:null;if(target!==null){e.preventDefault();tabs[target].click();tabs[target].focus()}}));
const sections=['start','journey','system','insights','reach','film'];let presenting=false,section=0;function move(n){section=(n+sections.length)%sections.length;document.getElementById(sections[section]).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});$('#section-label').textContent=`0${section+1} / 06`}
function present(on){presenting=on;document.body.classList.toggle('present',on);$('.present-controls').hidden=!on;$('#present').setAttribute('aria-pressed',on);$('#present').textContent=on?'Präsentation beenden ✕':'Präsentationsmodus ↗';if(on)move(0)}$('#present').onclick=()=>present(!presenting);$('#close-present').onclick=()=>present(false);$('#section-prev').onclick=()=>move(section-1);$('#section-next').onclick=()=>move(section+1);document.addEventListener('keydown',e=>{if(!presenting)return;if(e.key==='Escape')present(false);if(['BUTTON','VIDEO','A'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();move(section+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();move(section-1)}});
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){section=sections.indexOf(e.target.id);$('#section-label').textContent=`0${section+1} / 06`;$$('nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+e.target.id?'location':'false'))}},{threshold:.35});sections.forEach(id=>observer.observe(document.getElementById(id)));

// Native modal provides focus trapping and Escape handling.
const diagramDialog=$('#diagram-dialog'),diagramViewport=$('.diagram-viewport');let diagramZoom=1,diagramTrigger=null;
function setDiagramZoom(value){diagramZoom=Math.max(1,Math.min(4,value));$('#diagram-scale').textContent=Math.round(diagramZoom*100)+'%';diagramViewport.classList.toggle('zoomed',diagramZoom>1);$('#diagram-image').style.width=(diagramZoom*100)+'%';$('#diagram-minus').disabled=diagramZoom===1;$('#diagram-plus').disabled=diagramZoom===4;}
$$('[data-diagram]').forEach(button=>button.addEventListener('click',()=>{diagramTrigger=button;$('#diagram-title').textContent=button.dataset.title;$('#diagram-image').src=button.dataset.diagram;$('#diagram-image').alt=button.querySelector('img').alt;setDiagramZoom(1);diagramViewport.scrollTop=0;diagramViewport.scrollLeft=0;diagramDialog.showModal();document.body.classList.add('diagram-open');$('#diagram-close').focus();}));
$('#diagram-plus').onclick=()=>setDiagramZoom(diagramZoom+.5);$('#diagram-minus').onclick=()=>setDiagramZoom(diagramZoom-.5);$('#diagram-close').onclick=()=>diagramDialog.close();diagramDialog.addEventListener('close',()=>{document.body.classList.remove('diagram-open');diagramTrigger?.focus();});diagramDialog.addEventListener('keydown',e=>e.stopPropagation());
